Threaded solver
sebastianotronto/h48 pull request #3
Opened 2024-09-25 08:16 UTC by enricotenuti

I added the threaded version of the solver in a new file called thread.h. The threaded search uses a "thread poll" approach, the queue of tasks is created by a BFS search at depth 2 and then it is populated as tasks for the actual IDA*.

2024-09-25 09:02 UTC, enricotenuti commented
With the last commit I fixed some variables initialization, now there is a bug with the solutions vector when we use a higher number of threads.

2024-09-26 08:59 UTC, enricotenuti commented
The solutions vector had no termination character in the end and with the test cases provided the single thread solver was finding a different optimal solution and it didn't manifest the bug, differently by the version with 64 threads that was finding a solution with fewer characters. This fix works also with a higher number of solutions in the vector.

2024-09-28 16:45 UTC, sebastianotronto requested changes
After today's debugging session I have done a few more tests, and I am confident this works (save for the bug with 1-moves solutions; 2 movers seem to be fine).

As for performance, I have not tested it much but I found a factor of around 1.9 with 2 threads, which seems pretty good! I'll test with more threads when my PC is fixed.

I made only a couple of suggestions for renaming stuff. I think there are a few things that can be written in a simpler way, but I'll let you decide if and when to do it.

Before I merge this you have to
1. Fix the bug for 1-moves solutions. For example, `./run solve -solver h48 -options "0;4;20" -cube "$(./run frommoves -moves "F")"` returns an 8-mover as shortest solution.
2. Pull in the changes from master (there are couple of merge conflicts) and re-generate the h0k4 table for testing.

2024-09-28 16:45 UTC, sebastianotronto commented on src/solvers/h48/thread.h
> +STATIC int64_t solve_h48_parent(cube_t, int8_t, int8_t, int8_t, const void *, char *);
I suggest renaming this to `solve_h48_multithread`.

2024-09-28 16:45 UTC, sebastianotronto commented on src/solvers/h48/thread.h
> +#include <stdatomic.h>
Maybe a better name for this file is `solve_multithread.h`.

2024-09-28 16:50 UTC, sebastianotronto commented on src/solvers/h48/thread.h
> +	if (*arg->nsols == arg->maxsolutions)
I get a data race here (with line 50). The variable nsols should me mutex-guarded or made atomic.

2024-09-29 12:11 UTC, sebastianotronto approved these changes
Nice!

2024-09-29 12:12 UTC, merged